version: 0.2

phases:
   pre_build:
      commands:
         - python setup.py pytest

artifacts:
   type: zip
      files:
         - 'scripts/**/*'
         - 'app/**/*.py'
         - 'appspec.yml'
         - 'requirements.txt'
         - 'setup.py
         - 'run.py'

